app:
  name: "url-shortner"
  version: "1.0.0"

http_server:
  addr: "localhost:8081"
  timeout: "5s"
  idle_timeout: "5s"

logger_config:
  log_level: "debug"

postgres_config:
  dsn: "postgres://postgres:1879@localhost:5432/wildberries?sslmode=disable"
  slaves_dsn: [ ]
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "5m"

redis_config:
  addr: ":6379"
  password: ""
  db: 0

